### PR TITLE
Final Merge For XChain Orders Project For Polkadot Summer 2023 Hackathon

### PR DESCRIPTION
**Pull request by Entity54**

### CODE REVIEW

**Comment by juniuszhou** [comment]
- remove all .DS_Store files
- ignore the .yarn folder
- try to put all icons in a zip file

**Comment by Entity54** [comment]
Now ignoring .yarn folder and DS_Store files.
In the interests of time would rather avoid zipping the icons if possible.

**Comment by juniuszhou** [comment]
We can see lots of .DS_Store files, remove them. and code change just in your project's folder.

**Comment by Entity54** [comment]
Removed DS_Store files. Is this ok now please

**Comment by juniuszhou** [comment]
image

**Comment by Entity54** [comment]
Hi, 
I am not sure. Do you want me to do something else?
Is this now fixed?

I used for our project only 
rm 'projects/44-XChain_Orders/.DS_Store'
rm 'projects/44-XChain_Orders/src/.DS_Store'
rm 'projects/44-XChain_Orders/src/images/.DS_Store'

to remove the files you said to my colleague.

**Comment by juniuszhou** [comment]
remove hackathon-2023-summer/.DS_Store and hackathon-2023-summer/projects/.DS_Store.
remove .yarn/cache

**Comment by Entity54** [comment]
Hi,
Would it please be possible to have a look at this
I think I removed all files as you suggested
Could you check please

**Pull request merged**
